# GitHub Actions workflow to build OpenVPN and OpenSSL for Android on multiple architectures
# This file includes comments explaining each section

# Workflow metadata
name: Build OpenVPN for Android Multi-Arch

on:
  workflow_dispatch:
    inputs:
      openvpn_version:
        description: 'OpenVPN version'
        required: true
        default: '2.6.14'
      openssl_version:
        description: 'OpenSSL version'
        required: true
        default: '1.1.1w'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # Increased timeout to 6 hours for potentially long builds

    strategy:
      matrix:
        # Define target Android ABIs. Other values (host, api) will be derived.
        abi: # This must be a list of primitive values
          - "arm64-v8a"
          - "armeabi-v7a"
          - "x86"
          - "x86_64"

    steps:
    # Checkout the code
    - name: Checkout
      uses: actions/checkout@v4

    # Install required packages
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf automake libtool pkg-config libcap-ng-dev
        echo 'Installing system dependencies...';

    # Set up the Android NDK
    - name: Setup NDK
      id: setup_ndk_path # Added ID to reference outputs
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c

    # NEW STEP: Determine host and API based on ABI
    - name: Set Architecture Specific Variables
      id: arch_vars # Add ID to reference outputs for host and api
      run: |
        case "${{ matrix.abi }}" in
          "arm64-v8a")
            echo "host=aarch64-linux-android" >> "$GITHUB_OUTPUT"
            echo "api=21" >> "$GITHUB_OUTPUT"
            ;;
          "armeabi-v7a")
            echo "host=armv7a-linux-androideabi" >> "$GITHUB_OUTPUT"
            echo "api=21" >> "$GITHUB_OUTPUT"
            ;;
          "x86")
            echo "host=i686-linux-android" >> "$GITHUB_OUTPUT"
            echo "api=21" >> "$GITHUB_OUTPUT"
            ;;
          "x86_64")
            echo "host=x86_64-linux-android" >> "$GITHUB_OUTPUT"
            echo "api=21" >> "$GITHUB_OUTPUT"
            ;;
          *)
            echo "Unsupported ABI: ${{ matrix.abi }}"
            exit 1
            ;;
        esac
      shell: bash # Ensure bash is used for case statement and GITHUB_OUTPUT

    # Set environment variables for NDK and toolchains
    - name: Set up env
      run: |
        # Use the output from the 'setup_ndk_path' step to set environment variables
        echo "ANDROID_NDK_HOME=${{ steps.setup_ndk_path.outputs.ndk-path }}" >> $GITHUB_ENV
        echo "NDK_ROOT=${{ steps.setup_ndk_path.outputs.ndk-path }}" >> $GITHUB_ENV
        echo "${{ steps.setup_ndk_path.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

        # For good measure, also set them directly for the current shell context
        export ANDROID_NDK_HOME="${{ steps.setup_ndk_path.outputs.ndk-path }}"
        export NDK_ROOT="${{ steps.setup_ndk_path.outputs.ndk-path }}"
        export PATH="$PATH:${{ steps.setup_ndk_path.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin"


    # Download OpenVPN and OpenSSL sources
    - name: Download Sources
      run: |
        mkdir -p build
        cd build
        echo 'Downloading OpenVPN source...'; wget https://swupdate.openvpn.org/community/releases/openvpn-${{ github.event.inputs.openvpn_version }}.tar.gz
        echo 'Downloading OpenSSL source...'; wget https://www.openssl.org/source/openssl-${{ github.event.inputs.openssl_version }}.tar.gz
        echo 'Extracting OpenVPN source...'; tar -xzf openvpn-${{ github.event.inputs.openvpn_version }}.tar.gz
        echo 'Extracting OpenSSL source...'; tar -xzf openssl-${{ github.event.inputs.openssl_version }}.tar.gz
        
        # Verify extraction
        echo "Verifying OpenVPN source directory:"
        ls -ld openvpn-${{ github.event.inputs.openvpn_version }}
        echo "Verifying OpenSSL source directory:"
        ls -ld openssl-${{ github.event.inputs.openssl_version }}


    # Build OpenSSL statically for each architecture
    - name: Build OpenSSL
      run: |
        cd build/openssl-${{ github.event.inputs.openssl_version }}
        
        # Use outputs from the Set Architecture Specific Variables step
        local_api="${{ steps.arch_vars.outputs.api }}"
        local_abi="${{ matrix.abi }}" # ABI from matrix

        # OpenSSL Configure target mapping based on ABI
        # This part is still necessary as Configure needs a specific target string (e.g., android-arm64)
        case "${{ matrix.abi }}" in
          arm64-v8a) target_configure="android-arm64" ;;
          armeabi-v7a) target_configure="android-arm" ;;
          x86) target_configure="android-x86" ;;
          x86_64) target_configure="android-x86_64" ;;
        esac

        echo "Running OpenSSL Configure with target: $target_configure"; \
        ./Configure $target_configure -D__ANDROID_API__=${{ local_api }} \
          --prefix=$PWD/../openssl_${{ local_abi }} \
          no-shared no-tests -fPIC -DPIC

        # Execute make clean ONLY after Configure has generated the Makefile
        make clean || true 

        echo 'Running make for OpenSSL...'; make -j$(nproc)
        echo 'Installing OpenSSL libraries...'; 
        make install_sw

        # Verify OpenSSL installation
        echo "Contents of installed OpenSSL include directory:"
        ls -l $PWD/../openssl_${{ local_abi }}/include
        echo "Contents of installed OpenSSL lib directory:"
        ls -l $PWD/../openssl_${{ local_abi }}/lib


    # Build OpenVPN client statically for each architecture
    - name: Build OpenVPN
      run: |
        cd build
        
        # Use outputs from the Set Architecture Specific Variables step
        local_host="${{ steps.arch_vars.outputs.host }}"
        local_api="${{ steps.arch_vars.outputs.api }}"
        local_abi="${{ matrix.abi }}"

        mkdir -p openvpn_${{ local_abi }}
        cd openvpn_${{ local_abi }}

        export CC="${{ local_host }}${{ local_api }}-clang"
        export CXX="${{ local_host }}${{ local_api }}-clang++"
        export AR="${{ local_host }}-ar"
        export RANLIB="${{ local_host }}-ranlib"
        export STRIP="${{ local_host }}-strip"

        export CFLAGS="-fPIC -DPIC -O2 -DANDROID -D__ANDROID_API__=${{ local_api }}"
        export LDFLAGS="-Wl,-z,max-page-size=0x4000 -static-libgcc"
        export CPPFLAGS="-DANDROID -D__ANDROID_API__=${{ local_api }}"

        OPENSSL_INSTALL_DIR=$PWD/../openssl_${{ local_abi }}
        OPENSSL_CFLAGS="-I${OPENSSL_INSTALL_DIR}/include"
        OPENSSL_LIBS="-L${OPENSSL_INSTALL_DIR}/lib -lssl -lcrypto"

        ../openvpn-${{ github.event.inputs.openvpn_version }}/configure \
          --host=${{ local_host }} \
          --prefix=$PWD/install \
          --enable-static --disable-shared \
          --disable-debug --enable-small \
          --disable-plugins --disable-management \
          --disable-systemd --disable-iproute2 \
          --disable-dco --disable-selinux \
          --disable-lz4 --disable-lzo --disable-pkcs11 \
          --disable-server --disable-multi --disable-user-group \
          --disable-chroot --disable-capability-dropping \
          --disable-linuxdir --disable-dep-check \
          --without-cap-ng --with-crypto-library=openssl \
          "${OPENSSL_CFLAGS}" \
          "${OPENSSL_LIBS}"

        echo 'Running make for OpenVPN...'; make -j$(nproc)
        echo 'Installing OpenVPN binaries...'; make install

        # Verify OpenVPN installation
        echo "Contents of installed OpenVPN directory:"
        ls -l $PWD/install/sbin


    # Build JNI shared library wrappers (libopenvpn.so, etc.)
    - name: Create Shared Library
      run: |
        mkdir -p android_libs/lib/${{ matrix.abi }} # Use matrix.abi here
        mkdir -p src_lib

        cat > src_lib/libopenvpn.c << 'EOF'
        #include <jni.h>
        #include <stdlib.h>
        #include <unistd.h>
        #include <string.h>
        #include <sys/wait.h>
        #include <android/log.h>
        #define LOG_TAG "OpenVPN"
        #define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)
        
        // WARNING: Using system(cmd) for executing commands can be a security risk
        // if 'command' input is not strictly controlled and sanitized, as it may
        // allow for command injection vulnerabilities.
        // For production environments, consider using safer alternatives like
        // fork() and execve() with carefully managed arguments, or
        // dedicated Android APIs for process execution.
        JNIEXPORT jint JNICALL Java_com_example_OpenVPN_exec(JNIEnv* env, jobject obj, jstring command) {
            const char* cmd = (*env)->GetStringUTFChars(env, command, 0);
            int ret = system(cmd);
            (*env)->ReleaseStringUTFChars(env, command, cmd);
            return ret;
        }
        EOF

        echo "Compiling JNI shared library for ${{ matrix.abi }}..."; \
        # Use outputs from the Set Architecture Specific Variables step for CC
        ${{ steps.arch_vars.outputs.host }}${{ steps.arch_vars.outputs.api }}-clang -shared -fPIC -llog \
          -Wl,-z,max-page-size=0x4000 \
          -o android_libs/lib/${{ matrix.abi }}/libopenvpn.so \
          src_lib/libopenvpn.c

        cp android_libs/lib/${{ matrix.abi }}/libopenvpn.so android_libs/lib/${{ matrix.abi }}/libopvpnutil.so
        cp android_libs/lib/${{ matrix.abi }}/libopenvpn.so android_libs/lib/${{ matrix.abi }}/libovpnexec.so

    # Upload output artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openvpn-libs-${{ matrix.abi }}
        path: android_libs/lib/${{ matrix.abi }}
